### PR TITLE
Add ssr support

### LINKED ISSUE #31: Doesnt render on serverside
Hello, Firstly this package one of the best clamp packages ever seen but there is only one problem. Unfortunately, not working with server-side projects like Nuxt js and for this reason, does not render on the server-side. But also this is a big problem for SEO.

Also, you have 1 pull request about this issue :) Can you do this for us?

### PR DESCRIPTION
**Pull request by Sharsie**
Because the original author of the PR https://github.com/Justineo/vue-clamp/pull/28 made none of the requested changes, here's another PR - I briefly tested it, it does the same thing as the other PR, but introduces changes requested by @Justineo 
Also fixes #31

### CODE REVIEW

**Comment by MaazDev** [comment]
Any plant to merge it ?

**Comment by MaazDev** [comment]
I just tried it , and im still getting the error : 
`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

**Comment by Sharsie** [comment]
@MaazDev Can you provide me with the content you are passing into it? We've been using it for more than a month without any problems so far. But I cannot tell for sure if it supports more than just plaintext

**Comment by MaazDev** [comment]
My bad , i have to use the tag props to use it as a paragraph sorry , work fine :)

**Comment by voraczech** [comment]
Is there a chance to merge this? @Justineo @rndmerle @arnaudvalle

**Comment by arnaudvalle** [comment]
@voraczech sorry, I don't have any rights on this repo

**Comment by akagamina** [comment]
I think @Justineo were dead

**Pull request merged**
